server:
  port: 8010
  compression:
    enabled: true
#    mime-types: 
#      - application/json
#      - application/xml
#      - text/html
#      - text/xml
#      - text/plain
    min-response-size: 1
#logging:
#  level:
#     root: debug 
# Nacos registry address
dubbo:
  application:
#    name: dubbo-xc-admin
    qos:
      enable: false
  registry:
    #address: nacos://127.0.0.1:8848
    address: spring-cloud://localhost
  cloud:
    # The subscribed services in consumer side
    subscribed-services:  ${spring.application.name},xc-service 
 # provider:
    #host: 127.0.0.1   
    #?namespace=cbe53515-f2ac-4ce1-bf54-c3fd9259a1da
  protocol: 
#    name: nacos
    name: dubbo
    port: -1
 

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
        ip: ${NACOS_REGIST_IP:}
    bus:
      id: ${spring.application.name}:${server.port}
    stream:
      bindings:
        springCloudBusInput:
          destination: springCloudBus
        springCloudBusOutput:
          destination: springCloudBus
        input:
          send-message-timeout: 30000
          group: xc-binder-group
          destination: xc-binder-topic
          content-type: application/json
          consumer:
            concurrency: 20

      rocketmq:
        binder:
          nameServer: localhost:9876

    inetutils:
      preferred-networks: ${spring.networks:}





##请求和响应GZIP压缩支持 
feign:
  hystrix:
    enabled: false
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
    response:
      enabled: true

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试
  
  
ignore:
  startWith: /user/login,/user/regist,/test

xc: 
  executor: 
    enabled: true #启动线程池 
            