server:
  port: 8765

#okhttp请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

spring:
 
  cloud:
     gateway:
       discovery:
         locator:
           lowerCaseServiceId: true
           enabled: true
       routes:
        # =====================================
        - id: xc-admin
          uri: lb://xc-admin
          order: 8001
          predicates:
          - Path=/api/admin/**
          filters:
          - StripPrefix=2
        # ====test=================================    
        - id: aliyun_route
          uri: https://www.aliyun.com/
          predicates:
          - Path=/product/** 
            
     nacos:
        discovery:
          server-addr: ${spring.cloud.nacos.config.server-addr}

                
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false




xc: 
   sentinel: 
      serverAddr: ${spring.cloud.nacos.config.server-addr}
      dataId: gate-sentinel-json
      groupId: DEFAULT_GROUP
   gate:
    ignore:
      startWith: /   

