server:
  port: 8880

#okhttp请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

spring:
 
  cloud:
     gateway:
       discovery:
         locator:
           lowerCaseServiceId: true
           enabled: true
       routes:
        # =====================================
        - id: xc-admin
          uri: lb://xc-admin
          order: 8001
          predicates:
          - Path=/api/admin/**
          filters:
          - StripPrefix=2
     nacos:
        discovery:
          server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false


gate:
  ignore:
    startWith: /


