server:
  port: 8880

#okhttp请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

spring:
  cloud:
     gateway:
       discovery:
         locator:
           lowerCaseServiceId: true
           enabled: true
       routes:
        # =====================================
        - id: xc-admin
          uri: lb://xc-admin
          order: 8001
          predicates:
          - Path=/api/admin/**
          filters:
          - StripPrefix=2
        # ====test=================================    
        - id: aliyun_route
          uri: https://www.aliyun.com/
          predicates:
          - Path=/product/** 
            
     nacos:
        discovery:
          server-addr: ${spring.cloud.nacos.config.server-addr}
          ip: ${NACOS_REGIST_IP:}
  inetutils:
    preferred-networks: ${spring.networks:}
                
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 9000
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试


xc: 
   sentinel: 
      serverAddr: ${spring.cloud.nacos.config.server-addr}
      dataId: gate-sentinel-json
      groupId: DEFAULT_GROUP
   gate:
    ignore:
      startWith: /   

